#!/bin/sh

# Configure Modem
# This works on Revision: 16121.1000.00.01.01.39
echo -e "AT+GTAUTOCONNECT=1\r\n" > /dev/ttyUSB0
#echo -e "AT+GTUSBMODE=36\r\n" > /dev/ttyUSB0 # Not needed because we OEM firmware already set to 36

exit 0
