#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

FLAG=/tmp/atc-reboot.flag
DELAY=60

boot() {
    start
}

start_service() {
    logger -t atc-delayed-reboot "Service started, will check for flag after ${DELAY}s"
    procd_open_instance
    procd_set_param command /bin/sh -c "logger -t atc-delayed-reboot 'Waiting 60s before checking flag'; sleep 60; if [ -f /tmp/atc-reboot.flag ]; then logger -t atc-delayed-reboot 'Flag found, removing and rebooting'; rm -f /tmp/atc-reboot.flag; sync; reboot; else logger -t atc-delayed-reboot 'No flag found, exiting'; fi"
    procd_set_param respawn 0 0 0
    procd_close_instance
}
